### ISSUE TITLE
Data Source

### ISSUE THREAD

**Issue by jgollub1** [JeffSackmann/tennis_pointbypoint#10]
Hi Jeff,

Thanks so much for providing this data. Do you mind sharing where you got the point-by-point information from? I can't find data of this form anywhere else on the internet. Thanks,

-Jacob

**Comment by rcorty** [comment]
I would also be interested in learning about the source.

**Comment by JeffSackmann** [comment]
most of it was scraped from a major sportsbook website. I do not talk about it publicly because it's not an official API and I don't want them to take it down and/or make it more difficult to scrape.
